### ISSUE TITLE
Support for changing fonts please :-)

### ISSUE THREAD

**Issue by tpn** [microsoftfeedback/WinDbg-Feedback#10]
The default Consolas is far better than the old Courier Windbg font, but it would be great to be able to customize global font + size.  (Or some details on where to hack it in the js/css files that I think drive things now.)

**Comment by aluhrs13** [comment]
We added this in last month's release (1904). Just hit "Settings" on the home ribbon:
![image](https://user-images.githubusercontent.com/3189095/58495859-6769a900-812d-11e9-9565-2060ea39ad4c.png)

There are still some windows it doesn't support yet, we'll be updating those in the future.

**Comment by tpn** [comment]
Awesome, thanks @aluhrs13!
