### ISSUE TITLE
Massive delay in Locals window after copying values

### ISSUE THREAD

**Issue by LeadAssimilator** [microsoftfeedback/WinDbg-Feedback#132]
Clicking a Value field for an item in Locals, then copying the resulting selection and hitting escape or clicking away, causes the UI to freeze for a noticeably long time.

**Comment by jsschultz** [comment]
> Clicking a Value field for an item in Locals, then copying the resulting selection and hitting escape or clicking away, causes the UI to freeze for a noticeably long time.

Issue is fixed in WinDbgX version 1.2410.11001.0
