### ISSUE TITLE
File Access is denied

### ISSUE THREAD

**Issue by dcmcgo** [microsoftfeedback/WinDbg-Feedback#138]
I even changed the file attributes to read, but I still can't read the file.

**Comment by robertbud** [comment]
Me too

**Comment by Karim754249** [comment]
Hi, 

i share with you the manipulation that worked for me.

>Windbg properties 
> Go to the security tab and click on modify 
> Click on add 
>Click on advanced at the bottom left
>Click on search and search the authentified users, double click on this
>Click Ok
>Make sure that the “writes and execution” and “writes” boxes are checked and click Ok
>Apply 

Bye

**Comment by Karim754249** [comment]
Thank you for your comment, I deleted mine. I just wanted to share my solution, but I don't really know anything about it and it's better not to do anything.
