### ISSUE TITLE
WinDbg - Installer fails with error code 0x80D03002, Windows 10 Pro x64 22H2 (19045.3570)

### ISSUE THREAD

**Issue by kristapsesterlins** [microsoftfeedback/WinDbg-Feedback#143]
Hi,

Windbg.appinstaller from https://aka.ms/windbg/download fails with the error message:

_App installation failed with error message: error 0x80D03002: Opening the package from location windbg.msixbundle failed. (0x80d03002)_

Installing the full package works fine - https://windbg.download.prss.microsoft.com/dbazure/prod/1-0-0/windbg.appinstaller 

Event Viewer does not show anything useful:

_error 0x80D03002: Opening the package from location windbg.msixbundle failed._

_Error 0x80070002: Opening the Msixvc package from location windbg.msixbundle failed. Please check whether the Msixvc support services are installed._

_Appinstaller operation failed with error code 0x80D03002. Detail: Unknown error_

_AppX Deployment operation failed for package file:///C:/Temp/windbg.appinstaller with error 0x80D03002. The specific error text for this failure is: error 0x80D03002: Opening the package from location windbg.msixbundle failed._

Attached is the screenshot and Event Log data.

![Untitled](https://github.com/microsoftfeedback/WinDbg-Feedback/assets/92995128/e6ea1287-1154-4814-9983-bf38a0bece1f)
[AppXDeployment.zip](https://github.com/microsoftfeedback/WinDbg-Feedback/files/13235898/AppXDeployment.zip)

**Comment by lzybkr** [comment]
I haven't seen that error code before.

If I search for that error code, I do see plenty of tips on how to fix it. It's probably worth trying some of them. based on some quick internal searches, the workarounds that mention Delivery Optimization seem relevant.

The error mentioning msixvc is curious - that's not something we're using to the best of knowledge.

**Comment by geoff-m** [comment]
I got the same error message but with error code 0x80072ee2 on Windows 11

**Comment by kirsan31** [comment]
> I got the same error message but with error code 0x80072ee2 on Windows 11

Same here - error `0x80072EE2` on Win11 23H2.

**Comment by weliwita** [comment]
> I haven't seen that error code before.
> 
> If I search for that error code, I do see plenty of tips on how to fix it. It's probably worth trying some of them. based on some quick internal searches, the workarounds that mention Delivery Optimization seem relevant.
> 
> The error mentioning msixvc is curious - that's not something we're using to the best of knowledge.

yes, for me deleting HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization - DODownloadMode key and restart solved the issue.

**Comment by iamtimmy** [comment]
> yes, for me deleting HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization - DODownloadMode key and restart solved the issue.
For me too! tyvm

**Comment by kristapsesterlins** [comment]
Hi,

@weliwita - thanks for solution. I will close this issue, as it was due to the DeliveryOptimization policy (it also affects the New Microsoft Teams updates)
