### ISSUE TITLE
the debugging session could not be start acces to path "c" ssd is denied

### ISSUE THREAD

**Issue by Fangyanlin** [microsoftfeedback/WinDbg-Feedback#156]

**Comment by Drake385** [comment]
Hey, got the same problem, I can't open any .dmp files in WinDbg, someone got a solution ?

**Comment by MXQMaster** [comment]
Right-click on the .dmp file and choose Settings. Click on the Security Tab and choose Advanced
![2](https://github.com/microsoftfeedback/WinDbg-Feedback/assets/140380182/95252f64-6a4b-4986-ac9d-8a4a7a0f2777)

Change the owner of the file
![3](https://github.com/microsoftfeedback/WinDbg-Feedback/assets/140380182/9592dd5a-920c-48a6-84af-3239b8771f8a)

Add a principal with full rights
![4](https://github.com/microsoftfeedback/WinDbg-Feedback/assets/140380182/dfa7656c-7b9d-41fa-a015-26ce13e88ca2)

![6](https://github.com/microsoftfeedback/WinDbg-Feedback/assets/140380182/3db1c60f-5d8c-46da-897a-32dff5b89452)

Confirm your changes and close the Settings window
![7](https://github.com/microsoftfeedback/WinDbg-Feedback/assets/140380182/c9719d38-3e62-453e-a4ce-f68832956673)

Now you can open the file in WinDbg

**Comment by UncleDano** [comment]
This helped me, thanks.
By the way, my dump files are in C:\Windows\minidump folder instead of memory-dmp.  Any reason this could change?

**Comment by MXQMaster** [comment]
Here is a link that explains how to change the dump file location:
https://www.sevenforums.com/tutorials/204214-dump-file-change-default-location.html

**Comment by lzybkr** [comment]
Access is denied to non-administrators because the dump could contain data that only administrators should have access to. Open the dump as an admin and everything should work.
