### ISSUE TITLE
Install error:  Canot open application package

### ISSUE THREAD

**Issue by honeway** [microsoftfeedback/WinDbg-Feedback#159]
Package downloaded from https://aka.ms/windbg/download

![image](https://github.com/microsoftfeedback/WinDbg-Feedback/assets/6339134/6369dfec-3f05-45b3-a3e5-a86af45a5cc9)

System:
![image](https://github.com/microsoftfeedback/WinDbg-Feedback/assets/6339134/d6e74257-f37b-4bcb-be3a-6b44ae1fd1fa)

**Comment by zsqw123** [comment]
just because of u live in china, open package with vscode and directly download from this xml's link
![image](https://github.com/microsoftfeedback/WinDbg-Feedback/assets/49520432/a556f5f4-75db-404a-b871-f2f89399ec15)
