### ISSUE TITLE
The certificate of download link is outdated

### ISSUE THREAD

**Issue by hehua04** [microsoftfeedback/WinDbg-Feedback#160]
https://aka.ms/windbg/download redirected to the download site of windbg and the site's certificate is outdated. Please update it. Thank you.

**Comment by lzybkr** [comment]
Are you still seeing the issue?

The target of that link is: `https://windbg.download.prss.microsoft.com/dbazure/prod/1-0-0/windbg.appinstaller`.
When I check the target with a tool like https://dnschecker.org/ssl-certificate-examination.php, it reports the certificate is valid from 24-Dec-2023 to 21-Jun-2024.

**Comment by hehua04** [comment]
It is ok now, thank you!
