### ISSUE TITLE
shit doesnt work for me

### ISSUE THREAD

**Issue by FrRoseAngel** [microsoftfeedback/WinDbg-Feedback#163]
Exactly what I said, it can't access the DMP at all

**Comment by ledarh** [comment]
The .dmp files are saved to C:\Windows\Minidump by default. Saving the dmp file(s) has to be enabled, though, but it is by default. To check to see if your machine is saving them, hold Ctrl+R to open the Run dialog and run "sysdm.cpl" (you can also to Settings -> System -> About -> "Advanced system settings" (under Related settings on right)), click the Advanced tab, then under "Startup and Recovery," click Settings...

Ensure the checkboxes under System Failure are checked and the dump file location should be something like %SystemRoot%\MEMORY.DMP where you can find your system's dump files.

**Comment by lzybkr** [comment]
@ledarh is probably correct about the most common cause of "can't access" errors.

Launching the debugger as administrator will usually help.
