### ISSUE TITLE
电脑蓝屏终止DWV代码  分析0x133_ISR_nt!KeAccumulateTicks

### ISSUE THREAD

**Issue by 2328104291** [microsoftfeedback/WinDbg-Feedback#167]
电脑经常蓝屏且开不了机，重启七八次才有可能正常开机一次，希望有专业人员帮忙解答，非常感谢
[021724-12265-01.dmp](https://github.com/microsoftfeedback/WinDbg-Feedback/files/14319402/021724-12265-01.dmp)
![1708185725515](https://github.com/microsoftfeedback/WinDbg-Feedback/assets/160338894/b525393c-b44a-4869-aa26-cd960ce7359c)

**Comment by lzybkr** [comment]
This repo is for reporting issues with WinDbg, not to investigate random crashes. Your dump file may have already been sent to Microsoft directly for further investigation.
