### ISSUE TITLE
Win 11 Mini Dump Files

### ISSUE THREAD

**Issue by HC1Gunner** [microsoftfeedback/WinDbg-Feedback#174]
I've been having a lot of blue screen stops codes with either "Reference by Pointer or Driver Power State Failure". After A restart I had been opening and viewing files in the Minidump folder. Now all of sudden I can't access the dump files, they can't be opened, copied, zipped, or anything. If I double click on one, the app opens but, but then says basically that my access is denied. 
Why all of a sudden can I not access or copy these files?

**Comment by lzybkr** [comment]
If you are getting access denied trying to open a dump file, try launching the debugger as administrator - that should help.
