### ISSUE TITLE
BugCheck

### ISSUE THREAD

**Issue by mwiggins24** [microsoftfeedback/WinDbg-Feedback#175]
Good morning, I keep getting blue screens every time I walk away from my computer and come back and move my mouse to wake the screen. I can't figure it out. Please see below:

*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

CRITICAL_PROCESS_DIED (ef)
        A critical system process died
Arguments:
Arg1: ffff9d8e406ee080, Process object or thread object
Arg2: 0000000000000000, If this is 0, a process died. If this is 1, a thread died.
Arg3: 0000000000000000, The process object that initiated the termination.
Arg4: 0000000000000000

Debugging Details:
------------------

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 6030

    Key  : Analysis.Elapsed.mSec
    Value: 11207

    Key  : Analysis.IO.Other.Mb
    Value: 14

    Key  : Analysis.IO.Read.Mb
    Value: 0

    Key  : Analysis.IO.Write.Mb
    Value: 39

    Key  : Analysis.Init.CPU.mSec
    Value: 1530

    Key  : Analysis.Init.Elapsed.mSec
    Value: 15662

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 136

    Key  : Bugcheck.Code.KiBugCheckData
    Value: 0xef

    Key  : Bugcheck.Code.LegacyAPI
    Value: 0xef

    Key  : Bugcheck.Code.TargetModel
    Value: 0xef

    Key  : CriticalProcessDied.ExceptionCode
    Value: 3e363080

    Key  : CriticalProcessDied.ImageName
    Value: umpoext.dll

    Key  : CriticalProcessDied.ImageOffset
    Value: 1acd8

    Key  : CriticalProcessDied.ImageSize
    Value: 30000

    Key  : CriticalProcessDied.ImageTimestamp
    Value: b7a2dabf

    Key  : CriticalProcessDied.Process
    Value: svchost.exe

    Key  : CriticalProcessDied.Symbol
    Value: umpoext.dll!?QueueTimer@WnfCallback@@AEAAK_K0@Z

    Key  : CriticalProcessDied.WERReportId
    Value: 5e7faf1b-af0d-410f-88ed-5d9c7d466244

    Key  : Failure.Bucket
    Value: 0xEF_svchost.exe_DcomLaunch_BUGCHECK_CRITICAL_PROCESS_3e363080_umpoext.dll!?QueueTimer@WnfCallback@@AEAAK_K0@Z_umpoext!WnfCallback::WnfNotificationInternal

    Key  : Failure.Hash
    Value: {c84c9c6f-0268-be48-f5dd-90c8995ad224}

    Key  : Hypervisor.Enlightenments.Value
    Value: 0

    Key  : Hypervisor.Enlightenments.ValueHex
    Value: 0

    Key  : Hypervisor.Flags.AnyHypervisorPresent
    Value: 0

    Key  : Hypervisor.Flags.ApicEnlightened
    Value: 0

    Key  : Hypervisor.Flags.ApicVirtualizationAvailable
    Value: 0

    Key  : Hypervisor.Flags.AsyncMemoryHint
    Value: 0

    Key  : Hypervisor.Flags.CoreSchedulerRequested
    Value: 0

    Key  : Hypervisor.Flags.CpuManager
    Value: 0

    Key  : Hypervisor.Flags.DeprecateAutoEoi
    Value: 0

    Key  : Hypervisor.Flags.DynamicCpuDisabled
    Value: 0

    Key  : Hypervisor.Flags.Epf
    Value: 0

    Key  : Hypervisor.Flags.ExtendedProcessorMasks
    Value: 0

    Key  : Hypervisor.Flags.HardwareMbecAvailable
    Value: 1

    Key  : Hypervisor.Flags.MaxBankNumber
    Value: 0

    Key  : Hypervisor.Flags.MemoryZeroingControl
    Value: 0

    Key  : Hypervisor.Flags.NoExtendedRangeFlush
    Value: 0

    Key  : Hypervisor.Flags.NoNonArchCoreSharing
    Value: 0

    Key  : Hypervisor.Flags.Phase0InitDone
    Value: 0

    Key  : Hypervisor.Flags.PowerSchedulerQos
    Value: 0

    Key  : Hypervisor.Flags.RootScheduler
    Value: 0

    Key  : Hypervisor.Flags.SynicAvailable
    Value: 0

    Key  : Hypervisor.Flags.UseQpcBias
    Value: 0

    Key  : Hypervisor.Flags.Value
    Value: 131072

    Key  : Hypervisor.Flags.ValueHex
    Value: 20000

    Key  : Hypervisor.Flags.VpAssistPage
    Value: 0

    Key  : Hypervisor.Flags.VsmAvailable
    Value: 0

    Key  : Hypervisor.RootFlags.AccessStats
    Value: 0

    Key  : Hypervisor.RootFlags.CrashdumpEnlightened
    Value: 0

    Key  : Hypervisor.RootFlags.CreateVirtualProcessor
    Value: 0

    Key  : Hypervisor.RootFlags.DisableHyperthreading
    Value: 0

    Key  : Hypervisor.RootFlags.HostTimelineSync
    Value: 0

    Key  : Hypervisor.RootFlags.HypervisorDebuggingEnabled
    Value: 0

    Key  : Hypervisor.RootFlags.IsHyperV
    Value: 0

    Key  : Hypervisor.RootFlags.LivedumpEnlightened
    Value: 0

    Key  : Hypervisor.RootFlags.MapDeviceInterrupt
    Value: 0

    Key  : Hypervisor.RootFlags.MceEnlightened
    Value: 0

    Key  : Hypervisor.RootFlags.Nested
    Value: 0

    Key  : Hypervisor.RootFlags.StartLogicalProcessor
    Value: 0

    Key  : Hypervisor.RootFlags.Value
    Value: 0

    Key  : Hypervisor.RootFlags.ValueHex
    Value: 0

    Key  : SecureKernel.HalpHvciEnabled
    Value: 0

    Key  : WER.OS.Branch
    Value: vb_release

    Key  : WER.OS.Version
    Value: 10.0.19041.1

BUGCHECK_CODE:  ef

BUGCHECK_P1: ffff9d8e406ee080

BUGCHECK_P2: 0

BUGCHECK_P3: 0

BUGCHECK_P4: 0

FILE_IN_CAB:  MEMORY.DMP

PROCESS_NAME:  svchost.exe

CRITICAL_PROCESS:  svchost.exe

ERROR_CODE: (NTSTATUS) 0x3e363080 - <Unable to get error code text>

CRITICAL_PROCESS_REPORTGUID:  {5e7faf1b-af0d-410f-88ed-5d9c7d466244}

IMAGE_NAME:  umpoext.dll

MODULE_NAME: umpoext

FAULTING_MODULE: 00007ffe23e70000 umpoext

BLACKBOXBSD: 1 (!blackboxbsd)

BLACKBOXNTFS: 1 (!blackboxntfs)

BLACKBOXPNP: 1 (!blackboxpnp)

BLACKBOXWINLOGON: 1

STACK_TEXT:  
fffffb8a`ef087838 fffff800`14b0d842     : 00000000`000000ef ffff9d8e`406ee080 00000000`00000000 00000000`00000000 : nt!KeBugCheckEx
fffffb8a`ef087840 fffff800`14a0cbb7     : 00000000`00000000 fffff800`14513a19 00000000`00000002 fffff800`144eb06b : nt!PspCatchCriticalBreak+0x10e
fffffb8a`ef0878e0 fffff800`14899698     : ffff9d8e`00000000 00000000`00000000 ffff9d8e`406ee080 ffff9d8e`406ee4b8 : nt!PspTerminateAllThreads+0x17291b
fffffb8a`ef087950 fffff800`1489926c     : ffff9d8e`406ee080 00000000`00000000 00000053`94bffb7c fffff800`1488580a : nt!PspTerminateProcess+0xe0
fffffb8a`ef087990 fffff800`1460f4f5     : ffff9d8e`406ee080 ffff9d8e`3e363080 fffffb8a`ef087a80 ffff9d8e`406ee080 : nt!NtTerminateProcess+0x9c
fffffb8a`ef087a00 00007ffe`27ded5e4     : 00007ffe`27e62e03 00007ffe`27e976e4 00000053`94bffb40 00000000`00000000 : nt!KiSystemServiceCopyEnd+0x25
00000053`94bfe828 00007ffe`27e62e03     : 00007ffe`27e976e4 00000053`94bffb40 00000000`00000000 00007ffe`27d50000 : ntdll!NtTerminateProcess+0x14
00000053`94bfe830 00007ffe`27df562d     : 00007ffe`27e976e4 00000000`00000008 00007ffe`27d50000 00007ffe`27da2f76 : ntdll!TppWorkerpInnerExceptionFilter+0x5b
00000053`94bfe860 00007ffe`27ddc876     : 00000053`94bfe908 00000053`94bfe948 00007ffe`27da2f76 00000000`00000001 : ntdll!TppWorkerThread$filt$3+0x19
00000053`94bfe8a0 00007ffe`27decc4e     : 00007ffe`27e977a4 00000053`94bff570 00000053`94bffb40 00000053`94bfeec0 : ntdll!_C_specific_handler+0x96
00000053`94bfe910 00007ffe`27df23df     : 00000000`00000000 00000053`94bfeeb0 00000053`94bff570 00000000`00000000 : ntdll!_GSHandlerCheck_SEH+0x6a
00000053`94bfe940 00007ffe`27da14a4     : 00000000`00000000 00000053`94bfeeb0 00000053`94bff570 00000000`00000000 : ntdll!RtlpExecuteHandlerForException+0xf
00000053`94bfe970 00007ffe`27df0f0e     : 00000050`00000000 fffffffd`00000000 000001bf`b84070a0 00000000`00000007 : ntdll!RtlDispatchException+0x244
00000053`94bff080 00007ffe`23e8acd8     : 00007ffe`23e7791c 00000053`94bff898 00000000`00000001 000001bf`b84070a0 : ntdll!KiUserExceptionDispatch+0x2e
00000053`94bff828 00007ffe`23e7791c     : 00000053`94bff898 00000000`00000001 000001bf`b84070a0 00000000`0000009a : umpoext!WnfCallback::QueueTimer
00000053`94bff830 00007ffe`27db2df9     : 00000000`00000000 41c6013d`a3bc8875 00000000`00000001 000001bf`b8046798 : umpoext!WnfCallback::WnfNotificationInternal+0x59dc
00000053`94bff930 00007ffe`27db2a81     : 000001bf`00000000 000001bf`b8047c40 000001bf`00000000 00000000`00000000 : ntdll!RtlpWnfWalkUserSubscriptionList+0x249
00000053`94bffa10 00007ffe`27db28e0     : 00000000`00000000 000001bf`b8a5d850 00000000`00000000 00000000`00000000 : ntdll!RtlpWnfProcessCurrentDescriptor+0x105
00000053`94bffa90 00007ffe`27d60ebc     : 000001bf`b800d900 000001bf`b800da88 00000000`7ffe0386 00007ffe`27d60daa : ntdll!RtlpWnfNotificationThread+0x80
00000053`94bffaf0 00007ffe`27da2f76     : 000001bf`b800da88 000001bf`b807d1b0 00000000`00000000 000001bf`b90bfe80 : ntdll!TppExecuteWaitCallback+0xa4
00000053`94bffb40 00007ffe`264e7614     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!TppWorkerThread+0x456
00000053`94bffe40 00007ffe`27da26a1     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : KERNEL32!BaseThreadInitThunk+0x14
00000053`94bffe70 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21

SYMBOL_NAME:  umpoext!WnfCallback::WnfNotificationInternal+59dc

IMAGE_VERSION:  10.0.19041.1566

STACK_COMMAND:  .cxr; .ecxr ; kb

BUCKET_ID_FUNC_OFFSET:  59dc

FAILURE_BUCKET_ID:  0xEF_svchost.exe_DcomLaunch_BUGCHECK_CRITICAL_PROCESS_3e363080_umpoext.dll!?QueueTimer@WnfCallback@@AEAAK_K0@Z_umpoext!WnfCallback::WnfNotificationInternal

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {c84c9c6f-0268-be48-f5dd-90c8995ad224}

Followup:     MachineOwner
---------

**Comment by lzybkr** [comment]
The repo is for reporting feedback and bugs for WinDbg and is not a general support channel for crashes or bug checks.
