### ISSUE TITLE
DBG cannot download on microsoft.com

### ISSUE THREAD

**Issue by sliverwolf233** [microsoftfeedback/WinDbg-Feedback#185]
When I want to download  WindowsDBG on [Microsoft Learn 'link](https://windbg.download.prss.microsoft.com/dbazure/prod/1-0-0/windbg.appinstaller) is no work on 403 Forbidden

**Comment by lzybkr** [comment]
I've reproduced the 403, but retrying several minutes later on the same machine, the problem went away.

We'll investigate but I just wanted to comment to suggest retrying and hopefully you'll have better luck.

**Comment by sliverwolf233** [comment]
> I've reproduced the 403, but retrying several minutes later on the same machine, the problem went away.
> 
> We'll investigate but I just wanted to comment to suggest retrying and hopefully you'll have better luck.

I retry lot of time . I can be sure the wrong is on microsoft.com , not on my Network and GFW.

**Comment by sliverwolf233** [comment]
The question is fix thank for development team

**Comment by wangxk15** [comment]
It's not fixed! The Windbg still cannot be downloaded. 403 Forbidden

**Comment by lzybkr** [comment]
I just tried and the link works for me.

Is it still not working?

And if so, is there any additional information you can provide to help us track down the problem?

**Comment by sliverwolf233** [comment]
> I just tried and the link works for me.
> 
> Is it still not working?
> 
> And if so, is there any additional information you can provide to help us track down the problem?

Currently available on the Microsoft Docs page, Windbg is available, but he is always unstable in mainland China 
thx for your concern
