### ISSUE TITLE
No Access to minidump files

### ISSUE THREAD

**Issue by Carib909** [microsoftfeedback/WinDbg-Feedback#186]
I am on MY computer. I have no acces to the *.dmp files using WINDBG app installed from the Microsoft store. How is that possible? I cannot take possesion of the file either.

**Comment by Carib909** [comment]
I am the only Administrator?????

**Comment by lzybkr** [comment]
Yes, but have you launched the debugger with administrator privileges? You should see `(Administrator)` in the window title:

![image](https://github.com/microsoftfeedback/WinDbg-Feedback/assets/2148248/f6e5e2f2-2a51-4da2-a8a2-660f60804c29)

**Comment by B3ST-UN1T** [comment]
I tried to open it as an admin, but still cant open stupid minidump folder(((
