### ISSUE TITLE
Access Denied.

### ISSUE THREAD

**Issue by Bucks024** [microsoftfeedback/WinDbg-Feedback#194]
The debugging session could not be started: Access path C:\Windows\Minidumps\052524-10187-01.dmp' is denied.
My PC keeps restarting after a bug check and i need to find out what it is.

Kind Regards

Paul Buckingham

**Comment by lzybkr** [comment]
You need to launch the debugger as administrator to access these dumps as they may contain information only accessible to administrators.

**Comment by B3ST-UN1T** [comment]
Im run it as an admin and nothing, there might be other problem?
