### ISSUE TITLE
Freshly installed WinDbg preview won't start

### ISSUE THREAD

**Issue by rodwiddowson** [microsoftfeedback/WinDbg-Feedback#2]
On a relatively and fully upto date 1809 install
DbXDll could not load dbgeng.dll

The error window isn't cutable buit I have the png of the stack dump downloaded.

Notes
* This was before and after I downloaded the standard windbg
* This morning I deleted the install and started again.  Same problem

**Comment by aluhrs13** [comment]
Can you share the screenshot? Not being able to load dbgeng.dll isn't quite enough information to go off of.

**Comment by rodwiddowson** [comment]
![windbg](https://user-images.githubusercontent.com/249743/58267401-75a97500-7d7b-11e9-818a-69fb3172791b.png)

> Can you share the screenshot? 
willingly

**Comment by rodwiddowson** [comment]
ugh.  And I missed the key data point - a missing entry in the dll

**Comment by aluhrs13** [comment]
Thanks! This is an incompatibility with some other software (usually a graphics driver) on your system that's injecting an older version of DbgHelp into our process. Our release last month (1904) had some mitigation to this bug, but we have another fix coming in our next release (1905) that should resolve it. If it keeps happening after that release feel free to re-open this.

**Comment by rodwiddowson** [comment]
Vmware tools perhaps?

**Comment by aluhrs13** [comment]
Yep, VMWare tools is one of the known ones.

**Comment by MagicAndre1981** [comment]
I also have this in VMware. Hopefully the fix is out soon.

![image](https://user-images.githubusercontent.com/8274816/58789393-4e11a280-85ee-11e9-804b-b6276659528c.png)

**Comment by pixnblox** [comment]
Hey @aluhrs13 and others: I am encountering this same issue after integrating Visual Leak Detector into a Visual C++ application, i.e. `ERROR: Locating export "SymSetDiaSession" for DLL "C:\WINDOWS\SYSTEM32\dbgeng.dll"`. This works fine for some of my colleagues, but fails for me and others. Given the age of this issue, I assume I am using a complete release version of WinDbg. I am not using a virtual machine, and I tried removing NVIDIA GeForce Experience as suggested elsewhere, but that didn't help. Is there a way to diagnose which installed application is causing this? Or is there a more reliable fix? Thanks!

**Comment by e-t-l** [comment]
@aluhrs13 I'm also experiencing this problem. I had freshly installed WinDBG from Microsoft Store. Not running a VM. The only GPU is the integrated Intel one.
