### ISSUE TITLE
WinDbg can't open BSOD report

### ISSUE THREAD

**Issue by 1ir** [microsoftfeedback/WinDbg-Feedback#200]
Soo
![Picture](https://github.com/microsoftfeedback/WinDbg-Feedback/assets/68752483/befa76d4-6d44-4dff-a1d8-d28a36e29703)
How to fix that. Don't tell me about administrator, its NOT working.
![Picture 2](https://github.com/microsoftfeedback/WinDbg-Feedback/assets/68752483/94cfafd5-b674-4d05-8d4b-c410aff34343)

**Comment by Xing-xing233** [comment]
把文件放c盘外的盘符试试

**Comment by lzybkr** [comment]
You need to launch the debugger as administrator to access dumps that were created for elevated processes or the kernel.
