### ISSUE TITLE
Multiple missing PDBs for ntkrnlmp

### ISSUE THREAD

**Issue by haram** [microsoftfeedback/WinDbg-Feedback#202]
ntkrnlmp.pdb,34898958E6070CE1E0B4F363528E1F29,1
ntkrnlmp.pdb,1E4C1E14D068C8E7DD576B41531DD5A2,1
ntkrnlmp.pdb,19049140578DA51130512EC33791DE2A,1
ntkrnlmp.pdb,4DABE14CFC64762E4F97ACA933B4B9B4,1

I frequently run into missing PDBs for ntkrnlmp/ntoskrnl, is there a dedicated line for addressing these issues? I sent multiple emails to windbgfb@microsoft.com but never got any replies and the issues weren't addressed.

**Comment by lzybkr** [comment]
We need more than the file hashes to find the missing symbols. We need the build of Windows. Send that information in your email to windbgfb@microsoft.com and we'll hopefully find the appropriate symbols.
