### ISSUE TITLE
Code Syntax highlighting not working if File ends with Uppercase Letter (.C) instead of lowcase letter (.c)

### ISSUE THREAD

**Issue by baget** [microsoftfeedback/WinDbg-Feedback#21]
Syntax highlighting not working if File ends with Uppercase Letter (.C) instead of low case letter (.c)

1) During a debug section
2) Open test.**c** using "Open Source file..." button and see code Syntax highlighting  working
3) Close the File, rename it extension to ".C" (uppercase)
4) Open Again the same file and see there is no code syntax highlighting.

**Comment by TimMisiak** [comment]
Thanks for the report, this will be fixed in our next release.
