### ISSUE TITLE
WinDBG Preview still locks pdb files

### ISSUE THREAD

**Issue by gerhart01** [microsoftfeedback/WinDbg-Feedback#23]
When you debug driver in source mode, WinDBG Preview loads pdb file for that driver, but even if you unload driver, WinDBG locks pdb, and Visual Studio can't rewrite it during driver recompilation. Constantly have to restart WinDBG Preview every time, when driver changes.

I saw that behavior in WinDBG, but, i hope, it can be fixed in WinDBG Preview.

**Comment by aluhrs13** [comment]
If you add "cache*" to the front of your symbol path, that should fix this.

**Comment by gerhart01** [comment]
Thanks, advice works! With cache* option WinDBG Preview stops to lock driver pdb file immediately after driver unloaded in debugging OS.
