### ISSUE TITLE
New WinDbg spams "Error getting port connector information: 0x00000057" in kernel debugger output

### ISSUE THREAD

**Issue by gyroknight** [microsoftfeedback/WinDbg-Feedback#230]
**Target**
OS: Windows 11 24H2
CPU: Intel Core i7-14700K
Platform: Intel Z790

**Host**
OS: Windows 10 22H2
WinDbg version: 1.2409.17001.0

The messages are interlaced with the expected output from the kernel debugger. It does not appear when using legacy WinDbg in the same config.

**Comment by gr3yknigh1** [comment]
Absolutely the same behaviour.

**Comment by gr3yknigh1** [comment]
For me, it's only spamming when I open **network** kernel debugging. Even if I doesn't connected to guest.

**Comment by eadordzhiev** [comment]
Same here, I have only a single network adapter and the output is still spammed with those messages.
No issues on the old WinDbg, because these messages are printed only once right after it's started.

**Comment by lzybkr** [comment]
Thanks for the report. Internally this was fixed a couple weeks ago, so I think the fix should be available sometime next month.

**Comment by cyxap3k** [comment]
Having the same errors

**Comment by lzybkr** [comment]
We haven't released the fix externally yet - but we'll hopefully be doing so in the next week or so.

**Comment by qaz6750** [comment]
Still haven't provided the repaired program yet?

**Comment by lzybkr** [comment]
@qaz6750 - The release took longer than expected, but if you update to the latest, it should be fixed.
