### ISSUE TITLE
Provide a way to record TTD traces using console application

### ISSUE THREAD

**Issue by amithegde** [microsoftfeedback/WinDbg-Feedback#33]
Whenever I take a dump, it's from a prod VM to analyze complex workflows and issues surfaced on managed code because of native dependencies. Since the WinDBG gets installed from Microsoft store, it's kind of hard to copy over to a server to collect traces. Can you make it easy by providing a console application which collects traces which can be analyzed locally? Commercially available applications like dotTrace, dotMemory support this workflow to make over lives easier.

**Comment by bsld** [comment]
@amithegde Just copy over the Windows App folder to your desired location that you own - find windbg inside it and then look into target_architecture/tdd.
