### ISSUE TITLE
JavaScript ExecuteCommand("g") not behaving correctly

### ISSUE THREAD

**Issue by beevik** [microsoftfeedback/WinDbg-Feedback#55]
I've bound a JavaScript `.runscript` command to a breakpoint.  The script it runs calls `host.namespace.Debugger.Utility.Control.ExecuteCommand("g")` as its last command.  Unfortunately, the script only runs the first time the breakpoint is hit; it never runs on subsequent breakpoint hits.

Here is the `NotepadTest.js` script:
```javascript
"use strict";

 function invokeScript()
 {
    var ctl = host.namespace.Debugger.Utility.Control;
    host.diagnostics.debugLog("We're opening, let's continue!\n");
    ctl.ExecuteCommand("gc");
}
```

I'm using `C:\Windows\System32\notepad.exe` as the WinDbg target executable.  I've set a breakpoint on notepad's `ShowOpenSaveDialog` function with the following WinDbg command:
```
bp notepad!ShowOpenSaveDialog ".scriptrun C:\\WinDbg\\NotepadTest.js"
```

This issue has been reported previously [on StackOverflow](https://stackoverflow.com/questions/47715274/calling-javascript-functions-in-windbg-breakpoint-commands), but there was no resolution.

**Comment by Michael-ZecOps** [comment]
I was just about to post this. Here's a short video that demonstrates the bug:
https://streamable.com/bjnfa8

**Comment by Michael-ZecOps** [comment]
Here's an alternative approach, described by 0vercl0k in his blog, that works:
https://doar-e.github.io/blog/2017/12/01/debugger-data-model/#setting-breakpoints

**Comment by z2oh** [comment]
I'm not sure I follow the workaround mentioned above. As far as I can tell, this is still an issue.
