### ISSUE TITLE
Unable to view Extensionless C++ Standard Library Source

### ISSUE THREAD

**Issue by jtjohnson85-cer** [microsoftfeedback/WinDbg-Feedback#62]
When attempting to open C++ standard library headers in WinDbg Preview (1.0.2007.06001) the extension-less source file (i.e. xtree, algorithm...) fail to display any actual content in the file.

In addition *.py file source files do not display content as well. 

![WinDbgPreview](https://user-images.githubusercontent.com/79268383/108379660-c279e400-71cb-11eb-8aa3-309e5bd0cca3.PNG)

WinDbg Preview (1.0.2001.06001) is able to open and view the contents of these extension-less headers fine. 
Classic WinDbg is also able to open and view the contents of the headers. 

![image](https://user-images.githubusercontent.com/79268383/108380250-492ec100-71cc-11eb-89e8-2d54e287e127.png)

**Comment by aluhrs13** [comment]
@jtjohnson85-cer  - Thanks for the detailed report, this is a known issue that will be fixed in our next release later this month.
