### ISSUE TITLE
Refresh memory view on break

### ISSUE THREAD

**Issue by landaire** [microsoftfeedback/WinDbg-Feedback#72]
When reverse engineering projects I like to have a memory window open to examine how a buffer changes when I step through some code. Currently the behavior of the memory view is to only refresh when the *address* changes. This is particularly annoying for my use case as I have to type in a new random address, then type in the previous address again.

It would greatly improve my UX if this view instead automatically refreshed memory view contents when the debugger breaks.

**Comment by TimMisiak** [comment]
This should be fixed in the latest version that got released today on the microsoft store.
