### ISSUE TITLE
[Bug]WinDbgPreview crash on windows dev build 25295

### ISSUE THREAD

**Issue by pedoc** [microsoftfeedback/WinDbg-Feedback#89]
Running ``WinDbgPreview`` on ``windows 25295.1000`` crashes, tried uninstalling and reinstalling, but it doesn't work.

Here is the crash dump
[CrashDumps.zip](https://github.com/microsoftfeedback/WinDbg-Feedback/files/10728765/CrashDumps.zip)

**Comment by lzybkr** [comment]
This looks like an issue with Windows Insiders builds that affects other applications and is not related to WinDbg.

It looks like a fix is in progress and hopefully available in a newer Insiders build soon.
