### ISSUE TITLE
Why use version number 1.x?

### ISSUE THREAD

**Issue by chunhualiu** [microsoftfeedback/WinDbg-Feedback#92]
![image](https://user-images.githubusercontent.com/9837460/231996817-5446d5a4-d8ff-43f1-a44d-f396eb80c90e.png)

There are already WinDbg 10.x
Could not we use WinDbg 11.x as the version?

**Comment by lzybkr** [comment]
I agree it is a little confusing, but as long as we ship both the new and old clients, we must avoid the possibility of version number collisions.

By starting the new client as version 1.x, if the old client ever gets bumped to version 11.x (which could happen if Windows updates the version number that gets embedded in binaries), then we could get end up with such a conflict.
